server:
  port: "8082"

spring:
  profiles:
    active: qa

---
spring:
  profiles: dev
  datasource:
    username: hbstudent
    url: jdbc:mysql://localhost:3306/dcbapp?useSSL=false&serverTimezone=UTC
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"

welcome:
  message: Welcome to My HomePage!!!

---
spring:
  profiles: qa
  datasource:
    username: hbstudent
    url: jdbc:mysql://localhost:3306/dcbapp-qa?useSSL=false&serverTimezone=UTC
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"

management:
  endpoints:
    web:
      exposure:
        include: "health,features"

welcome:
  message: Welcome to My HomePage!!!

---
spring:
  profiles: prod
  datasource:
    username: hbstudent
    url: jdbc:mysql://localhost:3306/dcbapp-prod?useSSL=false&serverTimezone=UTC
    password: hbstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "true"

welcome:
  message: Welcome to My HomePage!!!
